
version: '3'
services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: back-app-android
    volumes:
      - ./postgres:/var/lib/postgresql/data


# version: '3.8'
# services:
#   db:
#     container_name: pg_container
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: root
#       POSTGRES_DB: back-app-android 
#     ports:
#       - "5432:5432"
#     volumes:
#       - ./data:/var/lib/postgresql/data
#   pgadmin:
#     container_name: pgadmin
#     image: dpage/pgadmin4
#     restart: always
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@admin.com
#       PGADMIN_DEFAULT_PASSWORD: root
#     ports:
#       - "5050:80"







